steps:
  - group: ":cypress: build e2e"
    steps:
    - label: build e2e
      key: "build-e2e"
      commands:
      - pushd e2e-tests; ./build-and-upload-image.sh; popd
      agents:
      - "role=node12"
  - wait
  - group: ":cypress: e2e tests"
    steps:
    - commands:
      - "pushd e2e-tests"
      - "./run-all-tests.sh"
      - "popd"
      label: ":test_tube: Running :cypress: E2E tests :test_tube:"
      key: "e2e-tests"
      agents:
      - "role=node12"
      parallelism: 14
      timeout_in_minutes: 30
      artifact_paths:
      - "e2e-tests/screenshots/**/*"
      - "e2e-tests/videos/**/*"
      - "e2e-tests/logs/*"
      plugins:
      - seek-oss/aws-sm#v2.3.1:
          json-to-env:
          - secret-id: "build-e2e-tests"
      retry:
        manual: false
        automatic:
        - exit_status: -1
          limit: 3
